import { ThemeType } from '../../../theme';
import { widthScale, heightScale, SCREEN_WIDTH } from '../../../utils/responsive';
import { StyleSheet } from 'react-native';

export const createStyles = (theme: ThemeType) =>
  StyleSheet.create({
    appIcon: {
      borderRadius: widthScale(12),
      height: widthScale(48),
      width: widthScale(48),
    },
    appInfo: {
      flex: 1,
      marginLeft: widthScale(12),
    },
    appItem: {
      alignItems: 'center',
      backgroundColor: theme.colors.withOpacity(theme.colors.surface, 0.4),
      borderRadius: widthScale(16),
      flexDirection: 'row',
      padding: widthScale(12),
    },
    appItemContainer: {
      marginBottom: heightScale(12),
      overflow: 'hidden',
    },
    appName: {
      ...theme.typography.body,
      color: theme.colors.textPrimary,
      fontSize: widthScale(16),
      fontWeight: '700' as const,
    },
    centered: {
      alignItems: 'center',
      flex: 1,
      justifyContent: 'center',
    },
    container: {
      backgroundColor: theme.colors.background,
      flex: 1,
    },
    emptyText: {
      ...theme.typography.body,
      color: theme.colors.textSecondary,
      fontSize: widthScale(14),
      marginTop: heightScale(40),
      textAlign: 'center',
    },
    fileItBtn: {
      alignItems: 'center',
      backgroundColor: theme.colors.primary,
      borderRadius: widthScale(12),
      height: heightScale(54),
      justifyContent: 'center',
      width: SCREEN_WIDTH - 80,
    },
    fileItBtnContainer: {
      alignItems: 'center',
      marginVertical: heightScale(20),
    },
    fileItText: {
      ...theme.typography.body,
      color: theme.colors.black,
      fontSize: widthScale(14),
      fontWeight: '800' as const,
      letterSpacing: 1,
      textTransform: 'uppercase',
    },
    limitSetter: {
      backgroundColor: theme.colors.withOpacity(theme.colors.surface, 0.6),
      borderBottomLeftRadius: widthScale(16),
      borderBottomRightRadius: widthScale(16),
      marginTop: heightScale(-4),
      overflow: 'hidden',
      paddingHorizontal: widthScale(20),
      width: '100%',
    },
    limitValueText: {
      ...theme.typography.h2,
      color: theme.colors.textPrimary,
      fontWeight: '800' as const,
      marginBottom: heightScale(10),
      marginTop: heightScale(20),
      textAlign: 'center',
    },
    limitValueTextManual: {
      ...theme.typography.h2,
      backgroundColor: theme.colors.grey800,
      borderRadius: widthScale(12),
      color: theme.colors.textPrimary,
      fontWeight: '800' as const,
      minWidth: widthScale(80),
      paddingHorizontal: widthScale(16),
      paddingVertical: heightScale(10),
      textAlign: 'center',
    },
    listContent: {
      paddingBottom: heightScale(40),
      paddingHorizontal: widthScale(16),
    },
    loadingText: {
      ...theme.typography.body,
      color: theme.colors.textSecondary,
      fontSize: widthScale(14),
      marginTop: heightScale(12),
    },
    manualInputRow: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'center',
      marginBottom: heightScale(20),
      marginTop: heightScale(24),
    },
    mascotStrip: {
      alignItems: 'center',
      backgroundColor: theme.colors.withOpacity(theme.colors.surface, 0.5),
      flexDirection: 'row',
      height: heightScale(60),
      paddingHorizontal: widthScale(20),
    },
    mascotText: {
      ...theme.typography.caption,
      color: theme.colors.textSecondary,
      flex: 1,
      fontSize: widthScale(13),
      fontWeight: '600' as const,
      lineHeight: heightScale(18),
      marginLeft: widthScale(12),
    },
    mascotThumb: {
      height: widthScale(40),
      resizeMode: 'contain',
      width: widthScale(40),
    },
    minLabel: {
      ...theme.typography.caption,
      color: theme.colors.textSecondary,
      fontSize: widthScale(16),
      fontWeight: '600' as const,
      marginLeft: widthScale(4),
    },
    quickChip: {
      backgroundColor: theme.colors.grey800,
      borderRadius: widthScale(20),
      marginHorizontal: widthScale(8),
      paddingHorizontal: widthScale(20),
      paddingVertical: heightScale(8),
    },
    quickChipText: {
      ...theme.typography.caption,
      color: theme.colors.textPrimary,
      fontSize: widthScale(12),
      fontWeight: '600' as const,
    },
    quickSelectRow: {
      flexDirection: 'row',
      justifyContent: 'center',
      marginVertical: heightScale(15),
    },
    searchContainer: {
      alignItems: 'center',
      backgroundColor: theme.colors.surface,
      borderRadius: widthScale(12),
      flexDirection: 'row',
      margin: widthScale(16),
      paddingHorizontal: widthScale(16),
    },
    searchInput: {
      color: theme.colors.textPrimary,
      flex: 1,
      fontSize: widthScale(16),
      height: heightScale(48),
      paddingHorizontal: widthScale(8),
    },
    selectedAppItem: {
      borderColor: theme.colors.cyan,
      borderWidth: 1,
    },
    sliderActiveTrack: {
      backgroundColor: theme.colors.cyan,
      borderRadius: widthScale(3),
      height: heightScale(6),
      position: 'absolute',
    },
    sliderContainer: {
      height: heightScale(40),
      justifyContent: 'center',
      marginVertical: heightScale(10),
      width: '100%',
    },
    sliderThumb: {
      backgroundColor: theme.colors.white,
      borderColor: theme.colors.cyan,
      borderRadius: widthScale(12),
      borderWidth: 2,
      height: widthScale(24),
      position: 'absolute',
      width: widthScale(24),
    },
    sliderTrack: {
      backgroundColor: theme.colors.grey800,
      borderRadius: widthScale(3),
      height: heightScale(6),
      width: '100%',
    },
    stampMark: {
      borderColor: theme.colors.black,
      borderRadius: widthScale(4),
      borderWidth: 1,
      opacity: 0.3,
      paddingHorizontal: widthScale(4),
      position: 'absolute',
      right: widthScale(15),
      top: heightScale(15),
      transform: [{ rotate: '-15deg' }],
    },
    stampMarkText: {
      color: theme.colors.black,
      fontSize: widthScale(8),
      fontWeight: '900' as const,
    },
    usageText: {
      ...theme.typography.caption,
      color: theme.colors.textSecondary,
      fontSize: widthScale(11),
      fontWeight: '600' as const,
      marginTop: heightScale(2),
    },
  });
