import json, re, os
OUT = os.path.dirname(os.path.abspath(__file__)) + "/out"
os.makedirs(OUT, exist_ok=True)

# id, category, intensity (None = any), text, apps (None = any), roaster (None = both), extra
def R(id, cat, lvl, text, apps=None, roaster=None, kinds=None, **extra):
    d = {"id": id, "category": cat, "intensity": lvl, "text": text, "apps": apps, "roaster": roaster, "kinds": kinds}
    d.update(extra)
    return d

P, H, S, U = "polite", "honest", "savage", "unhinged"

EN = [
# ---- limit hit
R("en_lh_p01","limit_hit",P,"That's your {app} time for today. The feed will survive without you."),
R("en_lh_p02","limit_hit",P,"{time} today. Your eyes would like a word."),
R("en_lh_p03","limit_hit",P,"{time} on {app} today. Let's call it a day, yeah?"),
R("en_lh_p04","limit_hit",P,"Limit reached. Your eyes have earned a break."),
R("en_lh_p05","limit_hit",P,"{app} will still be here tomorrow. Promise."),
R("en_lh_p06","limit_hit",P,"Time's up. Go look at something that doesn't refresh."),
R("en_lh_p07","limit_hit",P,"The reels will still be there tomorrow. This evening won't."),
R("en_lh_p08","limit_hit",P,"Enough scrolling for today. Your thumb has clocked out."),
R("en_lh_p09","limit_hit",P,"Close it now and today counts as a win."),
R("en_lh_p10","limit_hit",P,"{time} is plenty. The rest of your day is waiting."),
R("en_lh_h01","limit_hit",H,"{time} of other people's vacations. Your own life is on airplane mode."),
R("en_lh_h02","limit_hit",H,"You didn't lose track of time. You handed it over."),
R("en_lh_h03","limit_hit",H,"{opens} opens today. That's not a habit, that's a relationship."),
R("en_lh_h04","limit_hit",H,"{time} on {app}, and you couldn't name three things you saw."),
R("en_lh_h05","limit_hit",H,"Your limit was {limit}. You're at {time}. Math is not on your side."),
R("en_lh_h06","limit_hit",H,"You've watched strangers live for {time}. Want to try it yourself?"),
R("en_lh_h07","limit_hit",H,"{opens} opens. Your phone sees you more than your friends do."),
R("en_lh_h08","limit_hit",H,"{time} of content. None of it was about you."),
R("en_lh_h09","limit_hit",H,"{time} gone. That was a movie, a nap or a walk. You picked scrolling."),
R("en_lh_h10","limit_hit",H,"{over} over your limit. Your thumb didn't even hesitate."),
R("en_lh_s01","limit_hit",S,"{opens} opens today. At this point {app} should be paying you rent."),
R("en_lh_s02","limit_hit",S,"{time} on {app}. Your thumb gets more exercise than you do."),
R("en_lh_s03","limit_hit",S,"Another {time} donated to a billion-dollar company. Generous."),
R("en_lh_s04","limit_hit",S,"You're not \"just checking.\" You're moving in."),
R("en_lh_s05","limit_hit",S,"The feed has no ending. You were supposed to be the ending."),
R("en_lh_s06","limit_hit",S,"Your thumb ran a marathon today. The rest of you watched."),
R("en_lh_s07","limit_hit",S,"{over} over the limit. You and self-control are clearly on a break."),
R("en_lh_s08","limit_hit",S,"You've watched so much today your brain has started buffering."),
R("en_lh_s09","limit_hit",S,"Your hand opened {app} {opens} times today. Your brain agreed to none of them."),
R("en_lh_s10","limit_hit",S,"Still looking for something good in there? It left an hour ago."),
R("en_lh_u01","limit_hit",U,"Your phone has started calling you \"roommate.\""),
R("en_lh_u02","limit_hit",U,"At this rate, archaeologists will find you mid-scroll."),
R("en_lh_u03","limit_hit",U,"Breaking news: local human discovers {app} has no bottom. Keeps looking anyway."),
R("en_lh_u04","limit_hit",U,"I'm not mad. I'm just going to stare at you until you close it."),
R("en_lh_u05","limit_hit",U,"Your screen has your thumbprint memorised. You two should really see other people."),
R("en_lh_u06","limit_hit",U,"{opens} opens. At this point {app} opens itself out of habit. Like you."),
R("en_lh_u07","limit_hit",U,"Your battery has a longer attention span than you do today."),
R("en_lh_u08","limit_hit",U,"Keep scrolling and you'll reach the ads from 2019."),
R("en_lh_a01","limit_hit",H,"Another reel won't fix it. Neither did the last forty.",["instagram"]),
R("en_lh_a02","limit_hit",S,"{time} of other people's best moments. Here's one of yours: closing this.",["instagram"]),
R("en_lh_a03","limit_hit",H,"\"Just one more video\" has now been said {opens} times.",["youtube"]),
R("en_lh_a04","limit_hit",S,"Shorts are short. Your session isn't.",["youtube"]),
R("en_lh_a05","limit_hit",H,"Your streak is alive. Your evening isn't.",["snapchat"]),
R("en_lh_a06","limit_hit",S,"{time} of strangers arguing. Who won? Nobody.",["x"]),
R("en_lh_a07","limit_hit",H,"{time} on Reddit. You're now an expert in things you'll never need.",["reddit"]),
R("en_lh_a08","limit_hit",H,"{opens} opens today. Nobody texts that much. You just keep checking.",["whatsapp"]),
R("en_lh_l01","limit_hit",None,"I counted all {opens} of your opens today. We both need a hobby.",roaster="loop"),
R("en_lh_l02","limit_hit",None,"I'd be impressed by the dedication if it were to literally anything else.",roaster="loop"),
R("en_lh_l03","limit_hit",None,"My eyelids are this heavy and I'm a cartoon. Imagine yours.",roaster="loop"),
R("en_lh_l04","limit_hit",None,"I'm not even surprised. I'm just here.",roaster="lupe"),
R("en_lh_l05","limit_hit",None,"I expected this. I'm still disappointed.",roaster="lupe"),
R("en_lh_l06","limit_hit",None,"Go on, tell me it was \"just five minutes.\"",roaster="lupe"),
# ---- heads up (75%)
R("en_hu_p01","heads_up",P,"{left} left on {app}. Plenty of time to finish up and head out."),
R("en_hu_p02","heads_up",P,"Three quarters of your {app} time is gone. Pace yourself."),
R("en_hu_p03","heads_up",P,"{left} to go. Maybe skip the next rabbit hole."),
R("en_hu_p04","heads_up",P,"{left} left. Good moment to wrap up the video you're on."),
R("en_hu_h01","heads_up",H,"{left} left. That's a lot of reels, or one good decision."),
R("en_hu_h02","heads_up",H,"{time} down, {left} to go. Your thumb is warming up. So am I."),
R("en_hu_h03","heads_up",H,"{left} left. The algorithm is saving its best stuff for right now. Suspicious."),
R("en_hu_h04","heads_up",H,"{opens} opens so far today. I'm keeping count in case you aren't."),
R("en_hu_s01","heads_up",S,"{left} left. I've started stretching."),
R("en_hu_s02","heads_up",S,"{left} to go. I'm already picking out your roast."),
R("en_hu_s03","heads_up",S,"Three quarters gone. Your self-control is on 25% battery."),
R("en_hu_s04","heads_up",S,"{left} left. Enjoy it. I'm taking notes."),
R("en_hu_u01","heads_up",U,"{left} left. I've told your thumb to start packing."),
R("en_hu_u02","heads_up",U,"Countdown started. I'm warming up my eye roll."),
R("en_hu_u03","heads_up",U,"{left} left. The reels can sense fear."),
# ---- last call (90%)
R("en_lc_p01","last_call",P,"{left} left on {app}. Finish this one and call it."),
R("en_lc_p02","last_call",P,"Last few minutes. Good time to put the phone down on your own terms."),
R("en_lc_p03","last_call",P,"{left} to go. Close it now and it's your idea, not mine."),
R("en_lc_p04","last_call",P,"Almost at your limit. The feed will keep."),
R("en_lc_h01","last_call",H,"{left} left. After that, it's my turn to talk."),
R("en_lc_h02","last_call",H,"{left}. That's one video. Choose wisely."),
R("en_lc_h03","last_call",H,"You're {left} away from meeting me properly."),
R("en_lc_h04","last_call",H,"{left} left, {opens} opens today. You can see where this is going."),
R("en_lc_s01","last_call",S,"{left}. Close it now and nobody gets hurt."),
R("en_lc_s02","last_call",S,"{left} left. My roast is loaded and it's about you."),
R("en_lc_s03","last_call",S,"Last call. After this, the roast writes itself."),
R("en_lc_s04","last_call",S,"{left} left. I'd start saying goodbye to the feed."),
R("en_lc_u01","last_call",U,"{left} left. I've cleared my whole schedule for this."),
R("en_lc_u02","last_call",U,"{left}. I'm cracking my knuckles. I don't have knuckles. That's how ready I am."),
R("en_lc_u03","last_call",U,"Final warning. The next face you see in this app will be mine."),
# ---- snooze
R("en_sa_p01","snooze_ask",P,"Need a bit more time? Okay, but you'll have to earn it."),
R("en_sa_p02","snooze_ask",P,"Five more minutes. Let's make it official."),
R("en_sa_p03","snooze_ask",P,"Sure. One small task first."),
R("en_sa_h01","snooze_ask",H,"Oh? Convince me."),
R("en_sa_h02","snooze_ask",H,"Five more minutes. You said that {opens} opens ago."),
R("en_sa_h03","snooze_ask",H,"Fine. Type this and we'll pretend it was your idea."),
R("en_sa_s01","snooze_ask",S,"Negotiating with me? Bold. Type your confession."),
R("en_sa_s02","snooze_ask",S,"Five more minutes of what, exactly? Go on, type it."),
R("en_sa_s03","snooze_ask",S,"The feed won't miss you. But fine, prove you mean it."),
R("en_sa_u01","snooze_ask",U,"I've prepared a small ritual for you."),
R("en_sa_u02","snooze_ask",U,"Every snooze costs one sentence of dignity. Pay up."),
R("en_st_p01","snooze_sentence_1",P,"Just five more minutes, I promise."),
R("en_st_p02","snooze_sentence_1",P,"I will close it right after this."),
R("en_st_p03","snooze_sentence_1",P,"This is my last scroll today."),
R("en_st_h01","snooze_sentence_1",H,"I am choosing reels over my dreams."),
R("en_st_h02","snooze_sentence_1",H,"My thumb makes my decisions now."),
R("en_st_h03","snooze_sentence_1",H,"I know this video will not help me."),
R("en_st_s01","snooze_sentence_1",S,"I am losing an argument to an app."),
R("en_st_s02","snooze_sentence_1",S,"The algorithm knows me better than I do."),
R("en_st_s03","snooze_sentence_1",S,"I have no idea what I am looking for."),
R("en_st_u01","snooze_sentence_1",U,"I pledge my entire evening to the scroll."),
R("en_st_u02","snooze_sentence_1",U,"Please sir, may I have more reels."),
R("en_st_a01","snooze_sentence_1",H,"One more video will definitely fix my life.",["youtube"]),
R("en_st_a02","snooze_sentence_1",H,"I need to see one more stranger's holiday.",["instagram"]),
R("en_st2_01","snooze_sentence_2",None,"I, a fully grown adult, cannot stop watching strangers dance."),
R("en_st2_02","snooze_sentence_2",None,"I already used one snooze and I have learned absolutely nothing."),
R("en_st2_03","snooze_sentence_2",None,"My thumb has more free will than I do today."),
R("en_st2_04","snooze_sentence_2",None,"I promise this is really the last time, just like the last time."),
R("en_st2_05","snooze_sentence_2",None,"I am asking a cartoon for permission to keep going."),
R("en_st2_06","snooze_sentence_2",None,"I typed this whole sentence instead of closing the app."),
R("en_as_01","after_snooze",None,"Five minutes are up. The typing didn't shame you? Impressive, honestly."),
R("en_as_02","after_snooze",None,"That was your snooze. I hope the extra reels were life-changing."),
R("en_as_03","after_snooze",None,"Snooze over. You're right back where you started, minus five minutes."),
R("en_as_04","after_snooze",None,"You typed a confession for five more minutes. Bold trade."),
R("en_as_05","after_snooze",None,"Five minutes later: same feed, less evening."),
R("en_as_06","after_snooze",None,"Welcome back. I kept your seat warm. It's the roast seat."),
R("en_su_01","snoozes_used_up",None,"No. We're done here."),
R("en_su_02","snoozes_used_up",None,"Snoozes: zero. Excuses: also zero. Close it."),
R("en_su_03","snoozes_used_up",None,"You've used both. The only button left is the good one."),
R("en_su_04","snoozes_used_up",None,"I'd give you more time, but you'd just spend it here."),
R("en_cm_01","snooze_backout",None,"Look at you. Choosing yourself."),
R("en_cm_02","snooze_backout",None,"Good call. That sentence was going to haunt you."),
R("en_cm_03","snooze_backout",None,"Closed without a fight. I'm almost proud."),
R("en_cm_04","snooze_backout",None,"That counts as a win. I'm writing it down."),
# ---- late night
R("en_ln_01","late_night",None,"The feed will still be there tomorrow. Your sleep won't."),
R("en_ln_02","late_night",None,"{clock}. Nothing good has ever been posted at this hour."),
R("en_ln_03","late_night",None,"Your screen is the brightest thing in the room. Fix that."),
R("en_ln_04","late_night",None,"Every extra hour on your phone is linked to a later bedtime. Just saying.",fact=True),
R("en_ln_05","late_night",None,"Tomorrow-you is already tired, and it's your fault."),
R("en_ln_06","late_night",None,"{clock} and still scrolling. Your pillow has filed a complaint."),
R("en_ln_07","late_night",None,"This is the hour where \"one more reel\" becomes a lifestyle."),
R("en_ln_08","late_night",None,"Sleep now and tomorrow's scrolling will at least be well rested."),
# ---- wins
R("en_w_01","win_first_roast",None,"Closed on the first roast. I didn't even get to finish my sentence."),
R("en_w_02","win_first_roast",None,"You closed it. I'm not proud. I'm just not disappointed."),
R("en_w_03","win_streak",None,"{streak} days in a row of closing on the first roast. Who are you?",minStreak=3),
R("en_w_04","win_streak",None,"{streak}-day streak. I'm running out of things to say. Good.",minStreak=3),
R("en_w_05","win_perfect_day",None,"Yesterday: all under limits. I'm… proud? Weird feeling."),
R("en_w_06","win_perfect_day",None,"A whole day under every limit. I've never been this bored. Well done."),
R("en_w_07","win_lowered_limit",None,"Look at you."),
R("en_w_08","win_streak_7",None,"Seven days. Fine. I'm smiling. Don't make it weird."),
R("en_w_09","win_streak",None,"Day {streak}. Your thumb is starting to forget the way.",minStreak=5),
# ---- weekly report
R("en_wr_g01","weekly_good",None,"Fine. You did well. Don't let it go to your head."),
R("en_wr_g02","weekly_good",None,"{won_back} won back this week. I hope you did something great with it."),
R("en_wr_g03","weekly_good",None,"Less scrolling than last week. I'm suspicious, but impressed."),
R("en_wr_b01","weekly_bad",None,"You scrolled more than before you installed me. Impressive, in the worst way."),
R("en_wr_b02","weekly_bad",None,"{worst_time} on {worst_app}. That's a part-time job with no salary."),
R("en_wr_b03","weekly_bad",None,"{week_total} this week. Your thumb needs a holiday. So do you."),
R("en_wr_f01","weekly_first",None,"Week 1. The baseline is set. Now we see what you're made of."),
R("en_wr_f02","weekly_first",None,"First week done. I have notes. Many notes."),
R("en_wr_m01","weekly_mixed",None,"Some days you won, some days {worst_app} won. Rematch next week."),
# ---- home
R("en_hm_01","home_day1",None,"Day one. I'm taking notes."),
R("en_hm_02","home_under",None,"So far, so good. Don't ruin it."),
R("en_hm_03","home_under",None,"Quiet day. I like quiet days."),
R("en_hm_04","home_under",None,"Under every limit. I'm almost worried."),
R("en_hm_05","home_close",None,"Careful. {left} left on {app}. I'm watching."),
R("en_hm_06","home_close",None,"{app} is almost done for today. I've started stretching."),
R("en_hm_07","home_close",None,"One more long scroll on {app} and we're talking."),
R("en_hm_08","home_over",None,"I've seen worse. Not much worse, though."),
R("en_hm_09","home_over",None,"{app} already got you today. Let's keep it to one."),
R("en_hm_10","home_over",None,"Roasted on {app} already, and the day isn't over."),
R("en_cp_01","comparison",None,"That's an episode of something you actually like.",minMinutes=30),
R("en_cp_02","comparison",None,"That's a long walk you didn't take.",minMinutes=45),
R("en_cp_03","comparison",None,"That's a full gym session. Just saying.",minMinutes=60),
R("en_cp_04","comparison",None,"That's a whole lunch with friends, minus the friends.",minMinutes=90),
R("en_cp_05","comparison",None,"That's a whole movie you didn't watch.",minMinutes=120),
R("en_cp_06","comparison",None,"That's a full IPL match, strategic timeouts included.",minMinutes=180),
R("en_cp_07","comparison",None,"That's a Chennai to Bangalore train ride.",minMinutes=300),
R("en_cp_08","comparison",None,"That's a full night's sleep, spent awake.",minMinutes=480),

# ---- app kinds (chat, browser, games, shopping, work, video): lines only those apps get
R("en_k_ch01","limit_hit",P,"{time} of chatting today. The conversation will keep till tomorrow.",kinds=["chat"]),
R("en_k_ch02","limit_hit",P,"Everyone you were talking to will still be there tomorrow. Promise.",kinds=["chat"]),
R("en_k_ch03","limit_hit",H,"You're not waiting for a reply. You're waiting for a reason.",kinds=["chat"]),
R("en_k_ch04","limit_hit",H,"{opens} opens today. Nobody texts that much. You just keep checking.",kinds=["chat"]),
R("en_k_ch05","limit_hit",S,"Group chats don't need a live commentator. Put it down.",kinds=["chat"]),
R("en_k_ch06","limit_hit",S,"Left on read by your own self-control.",kinds=["chat"]),
R("en_k_ch07","limit_hit",U,"Your \"typing…\" has been typing for {time}.",kinds=["chat"]),
R("en_k_ch08","heads_up",P,"{left} left on {app}. Good time to send the last reply.",kinds=["chat"]),
R("en_k_ch09","heads_up",H,"{left} left. Wrap up the chat before the chat wraps you up.",kinds=["chat"]),
R("en_k_ch10","heads_up",S,"{left} left. Say \"ttyl\" and mean it this time.",kinds=["chat"]),
R("en_k_ch11","last_call",P,"{left} left. Send that last message and log off.",kinds=["chat"]),
R("en_k_ch12","last_call",H,"{left}. One reply. Not a whole thread.",kinds=["chat"]),
R("en_k_ch13","last_call",S,"{left} left. Type \"bye\" like you mean it.",kinds=["chat"]),
R("en_k_ch14","late_night",None,"{clock}. Whoever you're texting should be asleep too.",kinds=["chat"]),
R("en_k_ch15","late_night",None,"Nothing typed after midnight needs sending right now. Go to sleep.",kinds=["chat"]),
R("en_k_br01","limit_hit",P,"{time} in {app}. Close a few tabs. Start with this one.",kinds=["browser"]),
R("en_k_br02","limit_hit",H,"{time} of \"just looking something up\". What was it again?",kinds=["browser"]),
R("en_k_br03","limit_hit",H,"You opened {app} to search one thing. That was {time} ago.",kinds=["browser"]),
R("en_k_br04","limit_hit",S,"You have more tabs open than plans for today.",kinds=["browser"]),
R("en_k_br05","limit_hit",U,"Somewhere in tab 47 is the thing you came for. Leave it there.",kinds=["browser"]),
R("en_k_br06","heads_up",P,"{left} left in {app}. Find what you came for and close it.",kinds=["browser"]),
R("en_k_br07","heads_up",H,"{left} left. You searched one thing. This is page nine.",kinds=["browser"]),
R("en_k_br08","last_call",H,"{left}. Bookmark it. Leave.",kinds=["browser"]),
R("en_k_br09","last_call",S,"{left} left. That rabbit hole has a floor. It's me.",kinds=["browser"]),
R("en_k_br10","late_night",None,"{clock}, and you're searching things you'll forget by morning.",kinds=["browser"]),
R("en_k_gm01","limit_hit",P,"Game over for today. Real life has a save point too.",kinds=["games"]),
R("en_k_gm02","limit_hit",H,"{time} of \"one more round\". The rounds won.",kinds=["games"]),
R("en_k_gm03","limit_hit",S,"You've grinded {time}. Your real-life level hasn't moved.",kinds=["games"]),
R("en_k_gm04","limit_hit",U,"Achievement unlocked: {time} gone. Reward: nothing.",kinds=["games"]),
R("en_k_gm05","heads_up",P,"{left} left. Finish this round and save.",kinds=["games"]),
R("en_k_gm06","heads_up",H,"{left} left. That's one more round. Exactly one.",kinds=["games"]),
R("en_k_gm07","last_call",S,"{left}. Last round. I'm the final boss.",kinds=["games"]),
R("en_k_gm08","late_night",None,"{clock}. One more match turns into a sunrise.",kinds=["games"]),
R("en_k_sh01","limit_hit",P,"{time} of browsing. Your cart can wait till tomorrow.",kinds=["shopping"]),
R("en_k_sh02","limit_hit",H,"{time} on {app}. You've window-shopped longer than most people shop.",kinds=["shopping"]),
R("en_k_sh03","limit_hit",S,"Adding to cart is not a hobby. Close it.",kinds=["shopping"]),
R("en_k_sh04","limit_hit",U,"Your wishlist has a wishlist.",kinds=["shopping"]),
R("en_k_sh05","heads_up",H,"{left} left. Decide, or close it. Both are fine.",kinds=["shopping"]),
R("en_k_sh06","last_call",S,"{left}. Check out, or check out.",kinds=["shopping"]),
R("en_k_sh07","late_night",None,"{clock}. Nothing you add to cart at this hour is a good idea.",kinds=["shopping"]),
R("en_k_wk01","limit_hit",P,"{time} in {app} today. The inbox will still be full tomorrow. That's how inboxes work.",kinds=["work"]),
R("en_k_wk02","limit_hit",H,"Refreshing {app} doesn't make anyone reply faster.",kinds=["work"]),
R("en_k_wk03","limit_hit",S,"{opens} checks of {app}. Your work isn't in there. It's on your desk.",kinds=["work"]),
R("en_k_wk04","heads_up",P,"{left} left on {app}. Reply to the important one and close it.",kinds=["work"]),
R("en_k_wk05","last_call",H,"{left}. Send it or save it as a draft. Then go.",kinds=["work"]),
R("en_k_wk06","late_night",None,"{clock}. Work can wait until people are awake. Including you.",kinds=["work"]),
R("en_k_vd01","limit_hit",H,"Autoplay is not a reason. Close it.",kinds=["video"]),
R("en_k_vd02","limit_hit",S,"{time} of \"one more episode\". The credits were your exit.",kinds=["video"]),
R("en_k_vd03","heads_up",P,"{left} left. Finish this episode, not the next one.",kinds=["video"]),
R("en_k_vd04","last_call",H,"{left}. Not enough for another episode. Don't start one.",kinds=["video"]),
R("en_k_un01","late_night",None,"{clock}. Put the phone on charge and yourself to bed."),
]

TA = [
R("ta_lh_p01","limit_hit",P,"Boss, {time} aachu {app} app-la. Konjam break edunga."),
R("ta_lh_p02","limit_hit",P,"Innaiku {app} quota mudinjiduchu. Naalaiku paakalam."),
R("ta_lh_p03","limit_hit",P,"Feed engayum oda poradhu illa. Neenga konjam rest edunga."),
R("ta_lh_p04","limit_hit",P,"{time} podhum boss. Eyesku konjam rest kudunga."),
R("ta_lh_p05","limit_hit",P,"Ippo close panna kooda, streak-la neenga win pannalam."),
R("ta_lh_p06","limit_hit",P,"Limit reach aairuchu. Phone-a keela vechittu oru tea kudinga."),
R("ta_lh_p07","limit_hit",P,"Reels naalaikum irukum. Indha saayangalam thirumba varadhu."),
R("ta_lh_p08","limit_hit",P,"Seri, podhum. Screen time illadha edhavadhu pannunga."),
R("ta_lh_h01","limit_hit",H,"\"Innum oru reel dhaan\" nu {opens} thadava sollitteenga. Ippo naan solren: idhu dhaan last reel."),
R("ta_lh_h02","limit_hit",H,"{time} full-ah matha vanga vacation paatheenga. Unga life airplane mode-la irukku."),
R("ta_lh_h03","limit_hit",H,"{opens} thadava open panneenga. Idhu habit illa boss, love story."),
R("ta_lh_h04","limit_hit",H,"Unga limit {limit}. Ippo {time}. Kanakku unga side-la illa."),
R("ta_lh_h05","limit_hit",H,"{time} scroll panneenga, aana moonu video kooda nyabagam illa."),
R("ta_lh_h06","limit_hit",H,"Time pass-ku open panneenga. Time mothama pass aagiduchu."),
R("ta_lh_h07","limit_hit",H,"Unga phone unga friends-a vida ungala adhigama paakudhu."),
R("ta_lh_h08","limit_hit",H,"{over} limit-a thaandiyachu. Unga thumb yosikkave illa."),
R("ta_lh_h09","limit_hit",H,"Algorithm-ku unga weakness theriyum. Enakkum theriyum. Adhu idhu dhaan."),
R("ta_lh_h10","limit_hit",H,"{time}-la oru full padam paathu, interval-la popcorn-um saaptirukalam. Neenga reels paatheenga."),
R("ta_lh_s01","limit_hit",S,"{opens} thadava open pannirukeenga. {app}-ku rent kudukka aarambinga."),
R("ta_lh_s02","limit_hit",S,"Vera level scrolling. Aana life-la level onnum illa."),
R("ta_lh_s03","limit_hit",S,"{time} {app}-la. Unga thumb-ku unga-vida adhiga exercise."),
R("ta_lh_s04","limit_hit",S,"\"Just checking\" illa boss. Neenga anga kudi poiteenga."),
R("ta_lh_s05","limit_hit",S,"Unga thumb innaiku marathon odiduchu. Neenga ukkandhu vedikkai paatheenga."),
R("ta_lh_s06","limit_hit",S,"Feed-ku end-e illa. Neenga dhaan end-a irukanum."),
R("ta_lh_s07","limit_hit",S,"{over} limit thaandiyachu. Self-control-um neengalum breakup-la irukeenga pola."),
R("ta_lh_s08","limit_hit",S,"Nalla content innum varum-nu wait panreengala? Adhu oru mani neram munnadiye poiduchu."),
R("ta_lh_s09","limit_hit",S,"{time} {app}-la. Idhellam oru polappa?"),
R("ta_lh_s10","limit_hit",S,"Mudiyala boss. Neenga podhum-nu sollala-na, naan solren. Podhum."),
R("ta_lh_u01","limit_hit",U,"Unga thumb-ku oru statue vechidalam pola."),
R("ta_lh_u02","limit_hit",U,"Unga phone ungala \"roommate\"-nu kooppida aarambichuduchu."),
R("ta_lh_u03","limit_hit",U,"Indha speed-la ponga, archaeologists ungala scroll panra posture-laye kandupidipaanga."),
R("ta_lh_u04","limit_hit",U,"Breaking news: {app}-ku bottom-e illa-nu kandupidicha manushan, innum thedittu irukaar."),
R("ta_lh_u05","limit_hit",U,"Naan kovapadala. Close panra varaikum ungala muraichu paathutte iruppen."),
R("ta_lh_u06","limit_hit",U,"Unga phone 20% battery-la warning kudukudhu. Neenga 0% attention-la kooda scroll pannureenga."),
R("ta_lh_u07","limit_hit",U,"Innum scroll panna 1979 oda ads-e vandhudum."),
R("ta_lh_u08","limit_hit",U,"Unga screen-ku unga thumbprint manappaadam aairuchu. Rendu perum konjam break edunga."),
R("ta_lh_l01","limit_hit",None,"{opens} thadava open panneenga. Naan ellathaiyum count panniten. Enakkum velai illa, ungalukkum velai illa.",roaster="loop"),
R("ta_lh_l02","limit_hit",None,"Ivlo dedication vera edhula irundhaalum naan impress aagiruppen.",roaster="loop"),
R("ta_lh_l03","limit_hit",None,"Enakku shock-e illa. Expected dhaan.",roaster="lupe"),
R("ta_lh_l04","limit_hit",None,"Seri, \"just five minutes\" dhaan-nu sollunga. Kekaren.",roaster="lupe"),
R("ta_hu_p01","heads_up",P,"{left} dhaan irukku {app}-la. Mella wrap up pannunga."),
R("ta_hu_p02","heads_up",P,"Mukkaal quota mudinjiduchu. Konjam slow pannunga boss."),
R("ta_hu_h01","heads_up",H,"{left} irukku. Oru nalla decision edukka adhu podhum."),
R("ta_hu_h02","heads_up",H,"{time} aairuchu, {left} baaki. Unga thumb warm-up aagudhu. Naanum dhaan."),
R("ta_hu_s01","heads_up",S,"{left} baaki. Naan stretching aarambichitten."),
R("ta_hu_s02","heads_up",S,"{left} irukku. Enjoy pannunga. Naan notes eduthuttu irukken."),
R("ta_hu_u01","heads_up",U,"{left} baaki. Reels-ku unga bayam theriyum."),
R("ta_lc_p01","last_call",P,"{left} dhaan. Idha mudichittu close pannidunga."),
R("ta_lc_p02","last_call",P,"Ippo close panna adhu unga idea. Apram-na adhu en idea."),
R("ta_lc_h01","last_call",H,"{left} baaki. Adhukku apram en turn."),
R("ta_lc_h02","last_call",H,"{left}. Oru video-ku dhaan time irukku. Yosichu choose pannunga."),
R("ta_lc_s01","last_call",S,"{left}. Ippo close panna yaarukkum damage illa."),
R("ta_lc_s02","last_call",S,"{left} baaki. Roast ready aairuchu. Adhu unga-ah pathi dhaan."),
R("ta_lc_u01","last_call",U,"{left} baaki. Naan popcorn ready pannitten. Show aarambikka pogudhu."),
R("ta_sa_p01","snooze_ask",P,"Innum konjam time venuma? Seri, aana oru chinna velai irukku."),
R("ta_sa_h01","snooze_ask",H,"Oh? Convince pannunga."),
R("ta_sa_h02","snooze_ask",H,"Anju nimisham-a? Adha {opens} open-ku munnadiye sonneenga."),
R("ta_sa_s01","snooze_ask",S,"Ennoda negotiate panreengala? Dhairiyam dhaan. Confession-a type pannunga."),
R("ta_sa_s02","snooze_ask",S,"Feed ungala miss pannadhu. Aana seri, prove pannunga."),
R("ta_sa_u01","snooze_ask",U,"Snooze venuma? Oru chinna embarrassing line type pannunga. Terms and conditions apply."),
R("ta_st_p01","snooze_sentence_1",P,"Innum anju nimisham dhaan, promise."),
R("ta_st_p02","snooze_sentence_1",P,"Idhu mudinjadhum close pannidren."),
R("ta_st_h01","snooze_sentence_1",H,"Naan reels-ku adimai, en kanavu-ku illa."),
R("ta_st_h02","snooze_sentence_1",H,"En thumb dhaan ippo en boss."),
R("ta_st_s01","snooze_sentence_1",S,"Oru app kitta argument-la thothuttu irukken."),
R("ta_st_s02","snooze_sentence_1",S,"Naan enna thedren-nu enakke theriyala."),
R("ta_st_u01","snooze_sentence_1",U,"En saayangalam muzhusum scroll-ku samarpanam."),
R("ta_st_a01","snooze_sentence_1",H,"Innum oru video en life-a maathidum.",["youtube"]),
R("ta_st2_01","snooze_sentence_2",None,"Reels-a stop panna mudiyala."),
R("ta_st2_02","snooze_sentence_2",None,"Oru snooze use pannitten, innum onnume kathukala."),
R("ta_st2_03","snooze_sentence_2",None,"Close panradhukku badhila indha muzhu line-ayum type panniten."),
R("ta_as_01","after_snooze",None,"Anju nimisham mudinjiduchu. Type pannadhu kooda ungala shame pannala? Semma."),
R("ta_as_02","after_snooze",None,"Snooze over. Adhe feed, konjam kammiyana saayangalam."),
R("ta_as_03","after_snooze",None,"Back-ah? Roast ungalukkaga dhaan wait pannitu irundhuchu."),
R("ta_su_01","snoozes_used_up",None,"Illa. Mudinjiduchu. Podhum."),
R("ta_cm_01","snooze_backout",None,"Paarunga. Ungalukkaga neengale choose panneenga."),
R("ta_cm_02","snooze_backout",None,"Fight illama close panneenga. Konjam proud-ah irukku."),
R("ta_ln_01","late_night",None,"Feed naalaikum irukum. Unga thookam thirumba varadhu."),
R("ta_ln_02","late_night",None,"{clock}. Indha neraththula yaarum nalla content post panradhilla."),
R("ta_ln_03","late_night",None,"Room-la brightest thing unga screen dhaan. Adha maathunga."),
R("ta_ln_04","late_night",None,"{clock} aairuchu, innum scroll-a? Unga pillow complaint kuduthirukku."),
R("ta_ln_05","late_night",None,"Ippo thoongunga. Naalaiku scroll pannaalum fresh-ah pannalam."),
R("ta_w_01","win_first_roast",None,"First roast-laye close panneenga. Naan sentence-a mudikka kooda illa."),
R("ta_w_02","win_streak",None,"{streak} naal continuous-ah. Yaaruya nee?",minStreak=3),
R("ta_w_03","win_perfect_day",None,"Nethu ella limit-um kulla. Naan… proud-ah? Weird-ah irukku."),
R("ta_w_04","win_streak_7",None,"Ezhu naal. Seri, sirikkiren. Weird aakkadheenga."),
R("ta_w_05","win_lowered_limit",None,"Limit-a korachitteenga. Semma."),
R("ta_wr_g01","weekly_good",None,"Seri, nalla pannitteenga. Adhu thalaikku yeradha maathiri paathukkonga."),
R("ta_wr_g02","weekly_good",None,"{won_back} indha vaaram thirumba kidaichadhu. Adha nalla vishayathukku use pannirupeenganu nambaren."),
R("ta_wr_b01","weekly_bad",None,"Ennai install pannadhukku munnadi-ya vida adhigama scroll panneenga. Mosamana record."),
R("ta_wr_b02","weekly_bad",None,"{worst_time} {worst_app}-la. Sambalam illadha part-time velai."),
R("ta_wr_f01","weekly_first",None,"First week mudinjiduchu. Baseline set aairuchu. Ini dhaan aattam."),
R("ta_hm_01","home_day1",None,"Day one. Naan notes eduthuttu irukken."),
R("ta_hm_02","home_under",None,"Ippo varaikum ok. Kedukkaadheenga."),
R("ta_hm_03","home_close",None,"Careful. {app}-la {left} dhaan irukku. Naan paathuttu irukken."),
R("ta_hm_04","home_over",None,"Idhai vida mosamaana days paathirukken. Romba illa, aana paathirukken."),
R("ta_hm_05","home_over",None,"{app} ungala already pudichiduchu. Innaiku adhu mattum podhum."),
R("ta_cp_01","comparison",None,"Oru full padam paathirukalam.",minMinutes=120),
R("ta_cp_02","comparison",None,"Oru full IPL match, strategic timeout-oda.",minMinutes=180),
R("ta_cp_03","comparison",None,"Chennai to Bangalore train journey-ye mudinjirukum.",minMinutes=300),

# ---- app kinds
R("ta_k_ch01","limit_hit",P,"{time} chat panniyaachu. Pesura vishayam naalaikum irukkum.",kinds=["chat"]),
R("ta_k_ch02","limit_hit",H,"{opens} thadava open panneenga. Yaarum ivlo message anuppala. Neenga dhaan check pannittu irukeenga.",kinds=["chat"]),
R("ta_k_ch03","limit_hit",S,"Group chat-ku live commentary thevai illa boss. Phone-a vainga.",kinds=["chat"]),
R("ta_k_ch04","limit_hit",U,"Unga \"typing…\" {time}-a type pannittu irukku.",kinds=["chat"]),
R("ta_k_ch05","heads_up",P,"{left} dhaan irukku. Last reply-a anuppitu kelambunga.",kinds=["chat"]),
R("ta_k_ch06","last_call",H,"{left}. Oru reply podhum. Full thread venaam.",kinds=["chat"]),
R("ta_k_ch07","late_night",None,"{clock}. Neenga message panra aalum ippo thoonganum.",kinds=["chat"]),
R("ta_k_br01","limit_hit",P,"{time} {app}-la. Konjam tabs close pannunga. Idhula irundhu aarambinga.",kinds=["browser"]),
R("ta_k_br02","limit_hit",H,"Oru vishayam search panna vandheenga. Adhu {time} munnadi.",kinds=["browser"]),
R("ta_k_br03","limit_hit",S,"Innaiku plans-a vida adhigama tabs open-la irukku.",kinds=["browser"]),
R("ta_k_br04","heads_up",P,"{left} irukku. Thedi vandhadha kandupidichittu close pannunga.",kinds=["browser"]),
R("ta_k_br05","last_call",H,"{left}. Bookmark pannunga. Kelambunga.",kinds=["browser"]),
R("ta_k_br06","late_night",None,"{clock}. Kaalaila maranthu pora vishayatha ippo search panreenga.",kinds=["browser"]),
R("ta_k_gm01","limit_hit",P,"Innaiku game over. Real life-kum oru save point irukku.",kinds=["games"]),
R("ta_k_gm02","limit_hit",H,"\"Innum oru round\"-nu {time} aachu. Round dhaan jeyichuchu.",kinds=["games"]),
R("ta_k_gm03","limit_hit",S,"{time} grind panneenga. Real life level mattum ezhumbala.",kinds=["games"]),
R("ta_k_gm04","heads_up",P,"{left} irukku. Indha round-a mudichu save pannunga.",kinds=["games"]),
R("ta_k_gm05","last_call",S,"{left}. Last round. Final boss naan dhaan.",kinds=["games"]),
R("ta_k_gm06","late_night",None,"{clock}. Innum oru match-na sunrise-e paathuduveenga.",kinds=["games"]),
R("ta_k_sh01","limit_hit",P,"{time} browsing aachu. Cart naalaikum wait pannum.",kinds=["shopping"]),
R("ta_k_sh02","limit_hit",H,"{time} {app}-la. Vaangradha vida paakradhu dhaan adhigam.",kinds=["shopping"]),
R("ta_k_sh03","limit_hit",S,"Add to cart oru hobby illa boss. Close pannunga.",kinds=["shopping"]),
R("ta_k_sh04","heads_up",H,"{left} irukku. Decide pannunga, illa close pannunga.",kinds=["shopping"]),
R("ta_k_sh05","last_call",S,"{left}. Checkout pannunga, illa kelambunga.",kinds=["shopping"]),
R("ta_k_sh06","late_night",None,"{clock}. Indha neraththula cart-la podra edhuvum nalla idea illa.",kinds=["shopping"]),
R("ta_k_wk01","limit_hit",P,"{time} {app}-la. Inbox naalaikum full-ah dhaan irukkum. Adhu dhaan inbox.",kinds=["work"]),
R("ta_k_wk02","limit_hit",H,"{app}-a refresh panna yaarum seekiram reply panna maattaanga.",kinds=["work"]),
R("ta_k_wk03","heads_up",P,"{left} irukku. Important-a irukkradhukku reply panni close pannunga.",kinds=["work"]),
R("ta_k_wk04","late_night",None,"{clock}. Work message ellam kaalaila paathukalam. Ungalukkum dhaan.",kinds=["work"]),
R("ta_k_vd01","limit_hit",H,"Autoplay oru reason illa. Close pannunga.",kinds=["video"]),
R("ta_k_vd02","limit_hit",S,"\"Innum oru episode\"-nu {time} aachu. Credits dhaan unga exit.",kinds=["video"]),
R("ta_k_vd03","heads_up",P,"{left} irukku. Indha episode-a mudinga, next-a illa.",kinds=["video"]),
R("ta_k_vd04","last_call",H,"{left}. Innoru episode-ku time illa. Aarambikkaadheenga.",kinds=["video"]),
R("ta_k_un01","late_night",None,"{clock} aachu. Phone-a charge-la pottu neenga thoonga ponga."),
R("ta_k_un02","late_night",None,"Naalaiku-unga kaalai ippove tired-ah irukku. Unga thappu dhaan."),
]

# Which kinds of app a line fits (None = any app). Apps are mapped to a kind in src/roasts/kinds.ts.
KINDS = {"feed","video","chat","browser","games","shopping","work"}
FV = ["feed","video"]                          # reels, videos, the algorithm, strangers' lives
FEED = ["feed"]                                # posts, other people's holidays, ads
SCROLL = ["feed","video","browser","shopping"] # endless scrolling in general
KIND_TAGS = {
  # English
  "en_lh_p01":FV,"en_lh_p07":FV,"en_lh_p08":SCROLL,"en_lh_h01":FEED,"en_lh_h04":SCROLL,"en_lh_h06":FV,"en_lh_h08":FV,"en_lh_h09":SCROLL,
  "en_lh_s05":FEED,"en_lh_s08":FV,"en_lh_s10":SCROLL,"en_lh_u02":SCROLL,"en_lh_u03":SCROLL,"en_lh_u08":FEED,
  "en_hu_p03":SCROLL,"en_hu_p04":FV,"en_hu_h01":FV,"en_hu_h03":FV,"en_hu_u03":FV,
  "en_lc_p04":FV,"en_lc_h02":FV,"en_lc_s04":FV,"en_sa_s03":FV,
  "en_st_p03":SCROLL,"en_st_h01":FV,"en_st_h03":FV,"en_st_s02":FV,"en_st_u01":SCROLL,"en_st_u02":FV,
  "en_st2_01":FV,"en_as_02":FV,"en_as_05":FEED,
  "en_ln_01":FV,"en_ln_02":FEED,"en_ln_06":SCROLL,"en_ln_07":FV,"en_ln_08":SCROLL,"en_hm_07":SCROLL,
  # Tanglish
  "ta_lh_p03":FV,"ta_lh_p07":FV,"ta_lh_h01":FV,"ta_lh_h02":FEED,"ta_lh_h05":FV,"ta_lh_h09":FV,"ta_lh_h10":FV,
  "ta_lh_s02":SCROLL,"ta_lh_s06":FEED,"ta_lh_s08":SCROLL,"ta_lh_u03":SCROLL,"ta_lh_u04":SCROLL,"ta_lh_u06":SCROLL,"ta_lh_u07":FEED,
  "ta_hu_u01":FV,"ta_lc_h02":FV,"ta_sa_s02":FV,"ta_st_h01":FV,"ta_st_u01":SCROLL,"ta_st2_01":FV,"ta_as_02":FEED,
  "ta_ln_01":FV,"ta_ln_02":FEED,"ta_ln_04":SCROLL,"ta_ln_05":SCROLL,
}
for pack in (EN, TA):
    for r in pack:
        if r["id"] in KIND_TAGS: r["kinds"] = KIND_TAGS[r["id"]]
_ids = {r["id"] for r in EN + TA}
assert all(k in _ids for k in KIND_TAGS), [k for k in KIND_TAGS if k not in _ids]

PLACEHOLDERS = {"app","time","limit","opens","over","left","streak","clock","won_back","week_total","worst_app","worst_time"}
APP_KEYS = {
  "instagram": ["com.instagram.android"],
  "youtube": ["com.google.android.youtube"],
  "snapchat": ["com.snapchat.android"],
  "x": ["com.twitter.android"],
  "reddit": ["com.reddit.frontpage"],
  "whatsapp": ["com.whatsapp"],
}

def check(pack, lang):
    ids = set()
    for r in pack:
        assert r["id"] not in ids, r["id"]; ids.add(r["id"])
        for ph in re.findall(r"\{(\w+)\}", r["text"]):
            assert ph in PLACEHOLDERS, (r["id"], ph)
        assert r["intensity"] in (None, P, H, S, U)
        assert r["roaster"] in (None, "loop", "lupe")
        for a in (r["apps"] or []): assert a in APP_KEYS, (r["id"], a)
        for k in (r["kinds"] or []): assert k in KINDS, (r["id"], k)
        r["lang"] = lang
    return pack

def write(name, lang, pack):
    doc = {
        "pack": name, "lang": lang, "version": 1,
        "placeholders": sorted(PLACEHOLDERS),
        "appKeys": APP_KEYS,
        "notes": "intensity null = any level; apps null = any app; kinds null = any kind of app (feed, video, chat, browser, games, shopping, work); roaster null = both. snooze_sentence_* must be typed by the user; compare ignoring case and extra spaces. comparison lines use minMinutes; win_streak uses minStreak.",
        "roasts": check(pack, lang),
    }
    with open(f"{OUT}/{name}.{lang}.json", "w", encoding="utf-8") as f:
        json.dump(doc, f, ensure_ascii=False, indent=2)
    return len(pack)

n_en = write("core", "en", EN)
n_ta = write("core", "ta-Latn", TA)
manifest = {"version": 1, "packs": [
    {"file": "core.en.json", "lang": "en", "count": n_en},
    {"file": "core.ta-Latn.json", "lang": "ta-Latn", "count": n_ta}]}
json.dump(manifest, open(f"{OUT}/manifest.json","w"), indent=2)
from collections import Counter
print("en", n_en, dict(Counter(r["category"] for r in EN)))
print("ta", n_ta, dict(Counter(r["category"] for r in TA)))
