plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.superspider.endloop'
version = '0.1.0'

android {
  namespace "expo.modules.endloopcore"
  defaultConfig {
    versionCode 1
    versionName '0.1.0'
  }
}

dependencies {
  implementation 'androidx.core:core-ktx:1.13.1'
}
