import { StyleSheet, Platform, ViewStyle, TextStyle, ImageStyle } from 'react-native';
import { colors, spacing, typography } from '../../theme';

export const styles = StyleSheet.create({
  addBtn: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 16,
    elevation: 8,
    flexDirection: 'row',
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.m,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
  },
  addBtnText: {
    ...typography.body,
    color: colors.black,
    fontWeight: 'bold',
    marginLeft: spacing.s,
  } as TextStyle,
  appIcon: {
    borderRadius: 12,
    height: 48,
    width: 48,
  } as ViewStyle,
  appName: {
    ...typography.body,
    color: colors.textPrimary,
    fontWeight: 'bold',
  } as TextStyle,
  bubble: {
    backgroundColor: colors.grey800,
    borderColor: colors.border,
    borderRadius: 12,
    borderWidth: 1,
    left: spacing.m,
    maxWidth: '80%',
    padding: spacing.m,
    position: 'absolute',
    top: Platform.OS === 'ios' ? 100 : 60,
    zIndex: 100,
  } as ViewStyle,
  bubbleText: {
    ...typography.caption,
    color: colors.textPrimary,
    fontSize: 14,
  } as TextStyle,
  card: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 20,
    borderWidth: 1,
    elevation: 5,
    marginBottom: spacing.m,
    padding: spacing.m,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  } as ViewStyle,
  cardHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
  } as ViewStyle,
  cardMainInfo: {
    flex: 1,
    marginLeft: spacing.m,
  } as ViewStyle,
  cardPaused: {
    opacity: 0.6,
  } as ViewStyle,
  cardRow: {
    alignItems: 'center',
    flexDirection: 'row',
  } as ViewStyle,
  container: {
    backgroundColor: colors.background,
    flex: 1,
  } as ViewStyle,
  divider: {
    backgroundColor: colors.border,
    height: 32,
    marginHorizontal: spacing.m,
    width: 1,
  } as ViewStyle,
  editIcon: {
    marginLeft: spacing.s,
    opacity: 0.6,
  } as ViewStyle,
  emptyContainer: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: spacing.xl,
  } as ViewStyle,
  emptySubtitle: {
    ...typography.body,
    color: colors.textSecondary,
    marginBottom: spacing.xl,
    textAlign: 'center',
  } as TextStyle,
  emptyTitle: {
    ...typography.h2,
    marginBottom: spacing.s,
    textAlign: 'center',
  } as TextStyle,
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingBottom: spacing.m,
    paddingHorizontal: spacing.m,
    paddingTop: Platform.OS === 'ios' ? 60 : 20,
  } as ViewStyle,
  iconButton: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 12,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    width: 44,
  } as ViewStyle,
  leftHeader: {
    alignItems: 'center',
    flexDirection: 'row',
  } as ViewStyle,
  limitText: {
    ...typography.caption,
    color: colors.cyan,
    fontSize: 14,
    fontWeight: '600',
    marginTop: 2,
  } as TextStyle,
  listContent: {
    paddingBottom: spacing.xl,
    paddingHorizontal: spacing.m,
    paddingTop: spacing.s,
  } as ViewStyle,
  mascotLarge: {
    height: 200,
    marginBottom: spacing.l,
    resizeMode: 'contain',
    width: 200,
  } as ImageStyle,
  mascotSmall: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 16,
    borderWidth: 1,
    height: 32,
    marginRight: spacing.s,
    width: 32,
  } as ImageStyle,
  octagonIcon: {
    alignSelf: 'center',
    marginTop: 12,
  } as ViewStyle,
  progressBar: {
    borderRadius: 2,
    height: '100%',
  } as ViewStyle,
  progressContainer: {
    backgroundColor: colors.grey800,
    borderRadius: 2,
    height: 4,
    marginTop: spacing.s,
    overflow: 'hidden',
    width: '100%',
  } as ViewStyle,
  screenTitle: {
    ...typography.h2,
    color: colors.textPrimary,
  } as TextStyle,
  statusText: {
    ...typography.caption,
    color: colors.textSecondary,
    marginTop: spacing.xs,
  } as TextStyle,
  toggleContainer: {
    marginLeft: spacing.m,
  } as ViewStyle,
  toggleThumb: {
    backgroundColor: colors.white,
    borderRadius: 10,
    elevation: 2,
    height: 20,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    width: 20,
  } as ViewStyle,
  toggleTrack: {
    borderRadius: 12,
    height: 24,
    justifyContent: 'center',
    padding: 2,
    width: 44,
  } as ViewStyle,
});
