import { StyleSheet, Dimensions } from 'react-native';
import { ThemeType } from '../../../theme';

const { width } = Dimensions.get('window');

export const createStyles = (theme: ThemeType) =>
  StyleSheet.create({
    appIcon: {
      borderRadius: 12,
      height: 48,
      width: 48,
    },
    appInfo: {
      flex: 1,
      marginLeft: 12,
    },
    appItem: {
      alignItems: 'center',
      backgroundColor: theme.colors.withOpacity(theme.colors.surface, 0.4),
      borderRadius: 16,
      flexDirection: 'row',
      padding: 12,
    },
    appItemContainer: {
      marginBottom: 12,
      overflow: 'hidden',
    },
    appName: {
      ...theme.typography.body,
      color: theme.colors.textPrimary,
      fontWeight: '700' as const,
    },
    centered: {
      alignItems: 'center',
      flex: 1,
      justifyContent: 'center',
    },
    container: {
      backgroundColor: theme.colors.background,
      flex: 1,
    },
    deleteContainer: {
      alignItems: 'center',
      marginTop: 30,
      paddingBottom: 40,
    },
    deleteText: {
      ...theme.typography.caption,
      color: theme.colors.error,
      fontSize: 13,
      fontWeight: '600' as const,
      opacity: 0.8,
      textDecorationLine: 'underline',
    },
    emptyText: {
      ...theme.typography.body,
      color: theme.colors.textSecondary,
      marginTop: 40,
      textAlign: 'center',
    },
    fileItBtn: {
      alignItems: 'center',
      backgroundColor: theme.colors.primary,
      borderRadius: 12,
      height: 54,
      justifyContent: 'center',
      width: width - 80,
    },
    fileItBtnContainer: {
      alignItems: 'center',
      marginVertical: 20,
    },
    fileItText: {
      ...theme.typography.body,
      color: theme.colors.black,
      fontWeight: '800' as const,
      letterSpacing: 1,
      textTransform: 'uppercase',
    },
    limitSetter: {
      backgroundColor: theme.colors.withOpacity(theme.colors.surface, 0.6),
      borderBottomLeftRadius: 16,
      borderBottomRightRadius: 16,
      marginTop: -4,
      overflow: 'hidden',
      paddingHorizontal: 20,
      width: '100%',
    },
    limitValueText: {
      ...theme.typography.h2,
      color: theme.colors.textPrimary,
      fontWeight: '800' as const,
      marginBottom: 10,
      marginTop: 20,
      textAlign: 'center',
    },
    limitValueTextManual: {
      ...theme.typography.h2,
      backgroundColor: theme.colors.grey800,
      borderRadius: 12,
      color: theme.colors.textPrimary,
      fontWeight: '800' as const,
      minWidth: 80,
      paddingHorizontal: 16,
      paddingVertical: 10,
      textAlign: 'center',
    },
    listContent: {
      paddingBottom: 40,
      paddingHorizontal: 16,
    },
    loadingText: {
      ...theme.typography.body,
      color: theme.colors.textSecondary,
      marginTop: 12,
    },
    manualInputRow: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'center',
      marginBottom: 20,
      marginTop: 24,
    },
    mascotStrip: {
      alignItems: 'center',
      backgroundColor: theme.colors.withOpacity(theme.colors.surface, 0.5),
      flexDirection: 'row',
      height: 60,
      paddingHorizontal: 20,
    },
    mascotText: {
      ...theme.typography.caption,
      color: theme.colors.textSecondary,
      flex: 1,
      fontSize: 13,
      fontWeight: '600' as const,
      lineHeight: 18,
      marginLeft: 12,
    },
    mascotThumb: {
      height: 40,
      resizeMode: 'contain',
      width: 40,
    },
    minLabel: {
      ...theme.typography.caption,
      color: theme.colors.textSecondary,
      fontSize: 16,
      fontWeight: '600' as const,
      marginLeft: 4,
    },
    quickChip: {
      backgroundColor: theme.colors.grey800,
      borderRadius: 20,
      marginHorizontal: 8,
      paddingHorizontal: 20,
      paddingVertical: 8,
    },
    quickChipText: {
      ...theme.typography.caption,
      color: theme.colors.textPrimary,
      fontWeight: '600' as const,
    },
    quickSelectRow: {
      flexDirection: 'row',
      justifyContent: 'center',
      marginVertical: 15,
    },
    searchContainer: {
      alignItems: 'center',
      backgroundColor: theme.colors.surface,
      borderRadius: 12,
      flexDirection: 'row',
      margin: 16,
      paddingHorizontal: 16,
    },
    searchInput: {
      color: theme.colors.textPrimary,
      flex: 1,
      fontSize: 16,
      height: 48,
      paddingHorizontal: 8,
    },
    selectedAppItem: {
      borderColor: theme.colors.cyan,
      borderWidth: 1,
    },
    sliderActiveTrack: {
      backgroundColor: theme.colors.cyan,
      borderRadius: 3,
      height: 6,
      position: 'absolute',
    },
    sliderContainer: {
      height: 40,
      justifyContent: 'center',
      marginVertical: 10,
      width: '100%',
    },
    sliderThumb: {
      backgroundColor: theme.colors.white,
      borderColor: theme.colors.cyan,
      borderRadius: 12,
      borderWidth: 2,
      height: 24,
      position: 'absolute',
      width: 24,
    },
    sliderTrack: {
      backgroundColor: theme.colors.grey800,
      borderRadius: 3,
      height: 6,
      width: '100%',
    },
    stampMark: {
      borderColor: theme.colors.black,
      borderRadius: 4,
      borderWidth: 1,
      opacity: 0.3,
      paddingHorizontal: 4,
      position: 'absolute',
      right: 15,
      top: 15,
      transform: [{ rotate: '-15deg' }],
    },
    stampMarkText: {
      color: theme.colors.black,
      fontSize: 8,
      fontWeight: '900' as const,
    },
    usageText: {
      ...theme.typography.caption,
      color: theme.colors.textSecondary,
      fontWeight: '600' as const,
      marginTop: 2,
    },
  });
